Terraform 1
Otus-DevOps-2021-05/IvanPrivalov_infra pull request #5
Opened 2021-07-27 16:24 UTC by IvanPrivalov

# Выполнено ДЗ №6

 - [*] Основное ДЗ
 - [*] Задание со *

## В процессе сделано:
 - Настроены конфигурационные файлы Terraform и отработано создание VM.
 - Работа с Provisioners - деплой тестового приложения.
 - Вынос переменных в Inputs vars
 - Настройка балансировщика
 - Добавление второго инстанса в конфигурацию
 - Использование count

## Как запустить проект:
 - terraform init
 - terraform plan
 - terraform apply

## Как проверить работоспособность:
Apply complete! Resources: 4 added, 0 changed, 0 destroyed.

Outputs:

external_ip_address_app = [
  "178.154.223.158",
  "178.154.220.221",
]
lb_ip_address = tolist([
  "84.252.129.123",
])

Перейдите по ссылке http://84.252.129.123

## PR checklist
 - [*] Выставил label с номером домашнего задания
 - [*] Выставил label с темой домашнего задания

2021-07-27 17:35 UTC, IvanPrivalov commented
Добрый вечер. Подскажите пожалуйста в чем может быть проблема в тестах, уже всю голову сломал, ошибки ниже.
File .gitignore content should match /\n\Z/
File packer/variables.json.example content should match /\n\Z/
File terraform/terraform.tfvars.example content should match /\n\Z/

2021-07-27 21:19 UTC, mrgreyves requested changes
Здравствуйте!) Проверка пустых строк в конце файлов, бестпрактис все дела =)

2021-07-28 04:22 UTC, IvanPrivalov commented
Добрый день. Спасибо за помощь, целый день убил из-за 3х пустых строк)))

2021-07-28 08:24 UTC, mrgreyves approved these changes
Здравствуйте!) Проверил ваше дз. Все задания выполнены корректно, апрув!)

2021-07-28 08:24 UTC, mrgreyves commented on terraform/lb.tf
> +resource "yandex_lb_target_group" "app_lb_target_group" {
💪  💪  💪  💪

2021-07-28 11:11 UTC, merged